#!/bin/bash
echo "=== Final Shadow Configuration ==="
echo ""
echo "BEV Size: 2000x2000"
echo ""
echo "Tail (border shadow): 30px"
echo "  - Front: top 30px"
echo "  - Left: left 30px"  
echo "  - Back: bottom 30px"
echo "  - Right: right 30px"
echo ""
echo "Center shadow: 49%-51% = 40x40 px (2%)"
echo ""
echo "Effective viewing area: ~1960x1960 px (98%)"
echo ""
echo "Executable: ./bin/run_avm_new"
