#!/bin/bash

echo "=========================================="
echo "Optimized AVM Manual Calibration Test"
echo "=========================================="
echo ""
echo "OPTIMIZATIONS APPLIED:"
echo ""
echo "1. RESOLUTION IMPROVEMENT:"
echo "   - BEV size: 1000x1000 → 2000x2000 (4x pixels)"
echo "   - Pixel resolution: 1cm → 0.5cm per pixel"
echo "   - Window size: 1000x1000 → 1200x1200"
echo ""
echo "2. CENTER BLACK REGION REDUCED:"
echo "   - Size: 200x200 → 100x100 (75% reduction)"
echo ""
echo "3. BORDER SHADOW REDUCED:"
echo "   - Tail size: 300px → 150px (50% reduction)"
echo "   - Blend margin: 400px → 150px"
echo ""
echo "4. IMPROVED FUSION LOGIC:"
echo "   - Dynamic blend region calculation"
echo "   - Better corner blending"
echo "   - Cleaner separation between camera regions"
echo ""
echo "=========================================="
echo ""
echo "Testing executable..."
./bin/run_avm_new 2>&1 | head -10
echo ""
echo "Build successful! Optimizations applied."
echo ""
echo "Usage:"
echo "  ./bin/run_avm_new <images> <params> <extrinsics> 1"
echo ""
echo "Output stitching.png will be 2000x2000 resolution"
