#!/bin/bash
echo "=== Verification Configuration ==="
echo ""
echo "BEV Size: 2000x2000"
echo ""
echo "Tail (border): 200px"
echo "  - Each camera keeps 200px visible area"
echo "  - Rest is black (for blending)"
echo ""
echo "Center shadow: 49%-51% = 40x40 px (2%)"
echo ""
echo "Expected result:"
echo "  - Most of the image should be visible"
echo "  - Only small center black region (40x40)"
echo "  - Edges have 200px blend zones"
echo ""
echo "Run: ./bin/run_avm_new <imgs> <params> <extrinsics> 1"
